### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by psnippen** [ical4j/ical4j-connector#49]
@benfortuna can you provide a new release?

**Comment by benfortuna** [comment]
Yup, I started working on some changes but it's a bit significant. Hope to release in a week or two.

**Comment by psnippen** [comment]
Do you have a status update on this ticket?

**Comment by benfortuna** [comment]
Yes, have made for progress, but other priorities blocked me from releasing. I'll merge the changes to develop branch shortly, and release thereafter.

**Comment by benfortuna** [comment]
Note that I've just released v1.0.5 which includes some pending bug fixes, etc. The major refactor will be released shortly as a 2.0.0-alpha release.

**Comment by benfortuna** [comment]
@psnippen thx for the contributions. I will probably continue to release some alpha builds from the develop branch before merging to master for the first beta release.
