### ISSUE TITLE
Cannot connect to Baikal using PathResolver.BAIKAL

### ISSUE THREAD

**Issue by mikeberger** [ical4j/ical4j-connector#56]
I get: net.fortuna.ical4j.connector.ObjectStoreException: net.fortuna.ical4j.connector.FailedOperationException: Principals not found when using PathResolver.BAIKAL

My root url is http://10.0.0.190/baikal/html/dav.php

I debugged this a bit into your library and I just don't see how DavClient uses the root url. Does it only use the host and then try to call:

http://10.0.0.190/calendars... while dropping "/baikal/html/dav.php"?

For many years I have used a custom path resolver that prepends the "/baikal/html/dav.php" to the principal and user paths. Your server specific path resolvers do not prepend this part of the url and I don't see where DavClient does anything with it.
This always confused me. I probably should have written some bug reports 10 years ago when I first saw this.

This is not specific to the baikal PathResolver. I've tried others over the years and always went back to my custom PathResolver after failing to get them working.

**Comment by benfortuna** [comment]
Hi Mike,

Which version of the connector are you currently using? V2 is a big change from v1 , and I'm hoping to fix some of the inconsistencies in the previous version.

The challenge is the many different configurations required by caldav servers, but I hope to implement better testing to validate the correct paths.

If you have time please check the test source code to see if it makes sense, but I'll try to add some tests to replicate your issue.

**Comment by benfortuna** [comment]
And more specifically to your question, with V2 davclient we are trying to make it entirely stateless, so you can use it without the path resolver. I'll have a closer look at the docs to provide more examples of how to use v2.

**Comment by mikeberger** [comment]
Hi,

I was trying to upgrade from 1.0.1 to 1.0.5 just to keep current and pick up any bug fixes. I wasn't aware of V2 as IntelliJ was only showing the stable versions.

I'll stick with 1.0.1 for now. There's no reason to go to 1.0.5 if V2 is being developed.
