### ISSUE TITLE
Is ical4j-connector-1.0.5 still the latest stable version?

### ISSUE THREAD

**Issue by alanwaxman** [ical4j/ical4j-connector#58]
Hi Ben,

Just checking since there hasn't been an update or activity in a while though it works fine as is. 

The last version 2.0 branch was an alpha so would want to wait for an official stable version before transitioning to it.

Thanks in advance.

**Comment by benfortuna** [comment]
Hi alan, yes progress on v2 has been slow, but I have recently made some inroads towards finalizing the api changes (then will go beta).

Happy to know 1.0.5 still works for you. v2 won't be a drop-in replacement but hopefully an upgrade won't be too painful.

**Comment by alanwaxman** [comment]
Thanks for the confirmation Ben.
